# Faça um programa que leia um número inteiro qualquer e mostre na tela sua tabuada
tabuada = int(input('Digite um número para calcular a tabuada: '))
print(f'{tabuada} X 1 = {tabuada * 1}')
print(f'{tabuada} X 2 = {tabuada * 2}')
print(f'{tabuada} X 3 = {tabuada * 3}')
print(f'{tabuada} X 4 = {tabuada * 4}')
print(f'{tabuada} X 5 = {tabuada * 5}')
print(f'{tabuada} X 6 = {tabuada * 6}')
print(f'{tabuada} X 7 = {tabuada * 7}')
print(f'{tabuada} X 8 = {tabuada * 8}')
print(f'{tabuada} X 9 = {tabuada * 9}')
print(f'{tabuada} X 10 = {tabuada * 10}')
